server:
  port: 8083

spring:
  application:
    name: gateway-api


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: read-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/read/**
        - id: write-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/write/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/