server:
  port: 8083

spring:
  application:
    name: gateway-api


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: read-api
          uri: lb://READ-API
          predicates:
            - Path=/read/**
        - id: write-api
          uri: lb://WRITE-API
          predicates:
            - Path=/write/**


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


