server:
  port: 8083

spring:
  application:
    name: gateway-api

  redis:
    host: cache
    port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: read-api
          uri: lb://READ-API
          predicates:
            - Path=/read/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: write-api
          uri: lb://WRITE-API
          predicates:
            - Path=/write/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/





