server:
  port: 8081

spring:
  application:
    name: read-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/shortener?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    host: cache
    port: 6379
    timeout: 10000



eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/
