server:
  port: 8090

spring:
  application:
    name: read-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/shortener?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: cache
    port: 6379
    timeout: 10000



logging:
  level:
    io.lettuce.core: DEBUG
    org.springframework.data.redis: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/
