server:
  port: 8082


spring:
  application:
    name: write-api
  datasource:
    url: jdbc:mysql://db:3306/shortener?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect



eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8080/eureka/